import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link"
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className="navbar">
        <Link href="/">홈</Link>
        <Link href="/clubEvent">클럽이벤트</Link>
        <Link href="/gallery">활동내역</Link>
        <Link href="/aboutUs">우리에대해서</Link>
        <Link href="/userLogin">유저에대해서</Link>
      </div>
        {children}
      </body>
    </html>
  );
}
